[machine]
type = "sifive_u"
firmware = "tools/qemu/egos.bin"

[memory]
size = 16  # 单位为MB，直接写数值（无需引号或"M"后缀）

[smp]
cpus = 5   # 数值类型，去掉引号（原 smp-opts 改为标准 smp）

[drive]
if = "sd"
format = "raw"
file = "tools/disk.img"
