[machine]
type = "sifive_u"
firmware = "/home/bear/egos/egos-2000/tools/qemu/egos.bin"

[memory]
size = "16M"

[smp]
cpus = 5  # 数字不加引号

[drive]
if = "sd"
format = "raw"
file = "/home/bear/egos/egos-2000/tools/disk.img"
