[machine]
  type = "sifive_u"
  firmware = "/home/bear/egos/egos-2000/tools/qemu/egos.bin"

[memory]
  size = "16M"

[smp-opts]
  cpus = "5"

# CPU#0 is disabled in earth/boot.c, so there are effectively 4 cores.

[drive]
  if = "sd"
  format = "raw"
  file = "/home/bear/egos/egos-2000/tools/disk.img"

# QEMU (v7.0.0 or higher) supports SD card emulation for the sifive_u machine type.
